//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define smile                           157
#define IDB_BITMAP3                     159
#define IDB_practice2                   159
#define IDB_PNG1                        160
#define toolbar                         172
#define IDB_hi                          173
#define IDB_Blue                        177
#define IDB_BITMAP4                     178
#define IDB_Green                       178
#define IDB_PNG2                        184
#define IDB_BITMAP5                     185
#define IDB_PNG3                        194
#define IDB_PNG4                        195
#define IDR_JPG1                        197
#define IDB_BITMAP7                     199
#define IDB_PNG5                        203
#define IDB_PNG6                        204
#define mainpage                        205
#define left__wall                      209
#define left_wall                       209
#define right_wall                      212
#define IDB_PNG7                        217
#define IDB_BITMAP6                     218
#define map_floor                       220
#define front_wall                      222
#define IDB_PNG8                        224
#define IDB_BITMAP13                    225
#define map_door                        225
#define wood_floor                      226
#define big_grass                       227
#define lichen                          228
#define open_door                       229
#define small_grass                     230
#define sign                            231
#define water_hole                      232
#define level1_water                    233
#define stair_down                      236
#define stair_up                        237
#define IDB_hero                        238
#define startbutton                     239
#define warrior_icon                    240
#define mage_icon                       241
#define assassian_icon                  242
#define hunter_icon                     243
#define warrior                         244
#define mage                            245
#define hunter                          246
#define assassin                        247
#define warrior2                        248
#define ui_stop                         251
#define ui_detect                       252
#define ui_backpack                     253
#define ui_item1                        254
#define boss                            255
#define backpack_ui                     256
#define light_blue                      260
#define dark_red                        261
#define dark_green                      262
#define dark_red1                       263
#define dark_green1                     264
#define light_blue1                     265
#define arrow1b                         266
#define arrow2b                         267
#define food1b                          268
#define food2b                          269
#define grave                           270
#define key                             271
#define paper1s                         272
#define paper2s                         273
#define paper3s                         274
#define ring1b                          275
#define ring2b                          276
#define ring3b                          277
#define stick1b                         278
#define stick2b                         279
#define stick3b                         280
#define sword1b                         281
#define sword2b                         282
#define sword3b                         283
#define treasure                        284
#define food1s                          285
#define food2b1                         286
#define food2s                          286
#define boss2                           287
#define boss3                           288
#define IDB_BITMAP10                    289
#define boss4                           290
#define bat                             291
#define bat2                            292
#define bat3                            293
#define bat4                            295
#define bat5                            296
#define bat6                            297
#define bat7                            298
#define death_mon                       300
#define boss5                           301
#define boss6                           302
#define boss7                           303
#define boss8                           304
#define hp10                            307
#define hp1                             308
#define hp2                             309
#define hp3                             310
#define hp4                             311
#define hp5                             312
#define hp6                             313
#define hp7                             314
#define hp8                             315
#define hp9                             316
#define charactor_hunter_hp             319
#define charactor_mage_hp               321
#define charactor_assassin_hp           322
#define charactor_warrior_hp            323
#define herohp50                        338
#define herohp1                         338
#define finish                          343
#define blackbackground                 344
#define gameover                        345
#define letter_a                        347
#define letter_b                        348
#define letter_c                        349
#define letter_d                        350
#define letter_e                        351
#define letter_f                        352
#define letter_g                        353
#define letter_i                        355
#define letter_j                        356
#define letter_l                        358
#define letter_m                        359
#define letter_n                        360
#define letter_o                        361
#define letter_p                        362
#define letter_q                        363
#define letter_r                        364
#define letter_s                        365
#define letter_t                        366
#define letter_u                        367
#define letter_v                        368
#define letter_w                        369
#define letter_x                        370
#define letter_y                        371
#define letter_z                        372
#define gameoverBN                      373
#define paper1b                         375
#define IDB_PNG9                        376
#define paper2b                         377
#define IDB_PNG10                       378
#define paper3b                         379
#define IDB_PNG11                       380
#define ring1s                          381
#define ring2s                          382
#define ring3s                          383
#define cloth1b                         384
#define cloth2b                         385
#define cloth3b                         386
#define cloth1s                         387
#define cloth2s                         388
#define cloth3s                         389
#define sword1s                         390
#define sword2s                         391
#define sword3s                         392
#define stick1s                         393
#define stick2s                         394
#define stick3b1                        395
#define stick3s                         396
#define arrow1s                         397
#define arrow2s                         398
#define IDB_BITMAP11                    399
#define key1                            400
#define IDB_BITMAP28                    401
#define IDB_BITMAP29                    402
#define IDB_BITMAP8                     403
#define hero_status                     404
#define information                     406
#define letter_k                        407
#define letter_h                        408
#define word_assassin                   409
#define word_atk                        410
#define word_def                        411
#define word_hp                         412
#define word_hungry                     413
#define word_hunter                     414
#define word_mage                       415
#define word_warrior                    416
#define finalitem_b                     417
#define allbuff                         419
#define buff_hungry_little              420
#define buff_hungry_very                421
#define help_play                       424
#define help_information                425
#define item_information                426
#define warrior_attack1                 439
#define warrior_attack2                 440
#define warrior_attack3                 441
#define warrior_idle                    442
#define warrior_use1                    443
#define warrior_use2                    444
#define warrior_walk1                   445
#define warrior_walk2                   446
#define warrior_walk3                   447
#define warrior_walk4                   448
#define warrior_walk5                   449
#define warrior_walk6                   450
#define mage_attack1                    451
#define mage_attack2                    452
#define mage_attack3                    453
#define mage_idle                       454
#define mage_use1                       455
#define mage_use2                       456
#define mage_walk1                      457
#define mage_walk2                      458
#define mage_walk3                      459
#define mage_walk4                      460
#define mage_walk5                      461
#define mage_walk6                      462
#define ranger_attack1                  463
#define ranger_attack2                  464
#define ranger_attack3                  465
#define ranger_idle                     466
#define ranger_use1                     467
#define ranger_use2                     468
#define ranger_walk1                    469
#define ranger_walk2                    470
#define ranger_walk3                    471
#define ranger_walk4                    472
#define ranger_walk5                    473
#define ranger_walk6                    474
#define rogue_attack1                   475
#define rogue_attack2                   476
#define rogue_attack3                   477
#define rogue_idle                      478
#define rogue_use1                      479
#define rogue_use2                      480
#define rogue_walk1                     481
#define rogue_walk2                     482
#define rogue_walk3                     483
#define rogue_walk4                     484
#define rogue_walk5                     485
#define rogue_walk6                     486
#define warrior_attack1_l               487
#define warrior_attack2_l               488
#define warrior_attack3_l               489
#define warrior_idle_l                  490
#define warrior_walk1_l                 491
#define warrior_walk2_l                 492
#define warrior_walk3_l                 493
#define warrior_walk4_l                 494
#define warrior_walk5_l                 495
#define warrior_walk6_l                 496
#define mage_attack1_l                  497
#define mage_attack2_l                  498
#define mage_attack3_l                  499
#define mage_idle_l                     500
#define mage_walk1_l                    501
#define mage_walk2_l                    502
#define mage_walk3_l                    503
#define mage_walk4_l                    504
#define mage_walk5_l                    505
#define mage_walk6_l                    506
#define ranger_attack1_l                507
#define ranger_attack2_l                508
#define ranger_attack3_l                509
#define ranger_idle_l                   510
#define ranger_walk1_l                  511
#define ranger_walk2_l                  512
#define ranger_walk3_l                  513
#define ranger_walk4_l                  514
#define ranger_walk5_l                  515
#define ranger_walk6_l                  516
#define rogue_attack1_l                 517
#define rogue_attack2_l                 518
#define rogue_attack3_l                 519
#define rogue_idle_l                    520
#define rogue_walk1_l                   521
#define rogue_walk2_l                   522
#define rogue_walk3_l                   523
#define rogue_walk4_l                   524
#define rogue_walk5_l                   525
#define rogue_walk6_l                   526
#define warrior_l                       527
#define mage_l                          528
#define ranger_l                        529
#define rogue_l                         530
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        531
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
