//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define smile                           157
#define IDB_BITMAP3                     159
#define IDB_practice2                   159
#define IDB_PNG1                        160
#define toolbar                         172
#define IDB_hi                          173
#define IDB_Blue                        177
#define IDB_BITMAP4                     178
#define IDB_Green                       178
#define IDB_PNG2                        184
#define IDB_BITMAP5                     185
#define IDB_PNG3                        194
#define IDB_PNG4                        195
#define IDR_JPG1                        197
#define IDB_BITMAP7                     199
#define IDB_PNG5                        203
#define IDB_PNG6                        204
#define mainpage                        205
#define left__wall                      209
#define left_wall                       209
#define right_wall                      212
#define IDB_PNG7                        217
#define IDB_BITMAP6                     218
#define map_floor                       220
#define front_wall                      222
#define IDB_PNG8                        224
#define IDB_BITMAP13                    225
#define map_door                        225
#define wood_floor                      226
#define big_grass                       227
#define lichen                          228
#define open_door                       229
#define small_grass                     230
#define sign                            231
#define water_hole                      232
#define level1_water                    233
#define stair_down                      236
#define stair_up                        237
#define IDB_hero                        238
#define startbutton                     239
#define warrior_icon                    240
#define mage_icon                       241
#define assassian_icon                  242
#define hunter_icon                     243
#define warrior                         244
#define mage                            245
#define hunter                          246
#define assassin                        247
#define warrior2                        248
#define ui_stop                         251
#define ui_detect                       252
#define ui_backpack                     253
#define ui_item1                        254
#define boss                            255
#define backpack_ui                     256
#define light_blue                      260
#define dark_red                        261
#define dark_green                      262
#define dark_red1                       263
#define dark_green1                     264
#define light_blue1                     265
#define IDB_BITMAP8                     266
#define arrow1b                         266
#define IDB_BITMAP9                     267
#define arrow2b                         267
#define food1b                          268
#define food1ss                         268
#define food2b                          269
#define food2ss                         269
#define IDB_BITMAP12                    270
#define grave                           270
#define IDB_BITMAP14                    271
#define key                             271
#define IDB_BITMAP15                    272
#define paper1s                         272
#define IDB_BITMAP16                    273
#define paper2s                         273
#define IDB_BITMAP17                    274
#define paper3s                         274
#define IDB_BITMAP18                    275
#define ring1b                          275
#define IDB_BITMAP19                    276
#define ring2b                          276
#define IDB_BITMAP20                    277
#define ring3b                          277
#define IDB_BITMAP21                    278
#define stick1b                         278
#define IDB_BITMAP22                    279
#define stick2b                         279
#define IDB_BITMAP23                    280
#define stick3b                         280
#define IDB_BITMAP24                    281
#define sword1b                         281
#define IDB_BITMAP25                    282
#define sword2b                         282
#define IDB_BITMAP26                    283
#define sword3b                         283
#define IDB_BITMAP27                    284
#define treasure                        284
#define food1s                          285
#define food2b1                         286
#define food2s                          286
#define boss2                           287
#define boss3                           288
#define IDB_BITMAP10                    289
#define boss4                           290
#define bat                             291
#define bat2                            292
#define bat3                            293
#define bat4                            295
<<<<<<< HEAD
#define bat5                            296
#define bat6                            297
#define bat7                            298
#define IDB_BITMAP11                    299
#define death_mon                       300
#define boss5                           301
#define boss6                           302
#define boss7                           303
#define boss8                           304
#define hp10                            307
#define hp1                             308
#define hp2                             309
#define hp3                             310
#define hp4                             311
#define hp5                             312
#define hp6                             313
#define hp7                             314
#define hp8                             315
#define hp9                             316
#define charactor_hunter_hp             319
#define charactor_mage_hp               321
#define charactor_assassin_hp           322
#define charactor_warrior_hp            323
#define herohp50                        338
#define herohp1                         338
#define finish                          343
#define blackbackground                 344
#define gameover                        345
#define letter_a                        347
#define letter_b                        348
#define letter_c                        349
#define letter_d                        350
#define letter_e                        351
#define letter_f                        352
#define letter_g                        353
#define letter_i                        355
#define letter_j                        356
#define letter_h                        357
#define letter_l                        358
#define letter_m                        359
#define letter_n                        360
#define letter_o                        361
#define letter_p                        362
#define letter_q                        363
#define letter_r                        364
#define letter_s                        365
#define letter_t                        366
#define letter_u                        367
#define letter_v                        368
#define letter_w                        369
#define letter_x                        370
#define letter_y                        371
#define letter_z                        372
#define gameoverBN                      373
#define IDB_BITMAP28                    374
=======
#define paper1b                         296
#define IDB_PNG9                        296
#define paper2b                         297
#define IDB_PNG10                       297
#define paper3b                         298
#define IDB_PNG11                       298
#define ring1s                          299
#define ring2s                          300
#define ring3s                          301
#define cloth1b                         302
#define cloth2b                         303
#define cloth3b                         304
#define cloth1s                         305
#define cloth2s                         306
#define cloth3s                         307
#define sword1s                         308
#define sword2s                         309
#define sword3s                         310
#define stick1s                         311
#define stick2s                         312
#define stick3b1                        313
#define stick3s                         313
#define arrow1s                         314
#define arrow2s                         315
#define IDB_BITMAP11                    316
#define key1                            317
#define IDB_BITMAP28                    318
#define IDB_BITMAP29                    319
>>>>>>> chun
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
<<<<<<< HEAD
#define _APS_NEXT_RESOURCE_VALUE        375
=======
#define _APS_NEXT_RESOURCE_VALUE        321
>>>>>>> chun
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
